development:
  adapter: mysql
  database: AddDeadSimpleWebServiceSupportToExistingActions_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: AddDeadSimpleWebServiceSupportToExistingActions_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: AddDeadSimpleWebServiceSupportToExistingActions_production
  username: root
  password: 
  socket: /tmp/mysql.sock
