development:
  adapter: mysql
  database: SmartPluralizationOfWords_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: SmartPluralizationOfWords_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: SmartPluralizationOfWords_production
  username: root
  password: 
  socket: /tmp/mysql.sock
