development:
  adapter: mysql
  database: ManyToManyWithAttributesOnTheRelationship_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: ManyToManyWithAttributesOnTheRelationship_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: ManyToManyWithAttributesOnTheRelationship_production
  username: root
  password: 
  socket: /tmp/mysql.sock
