development:
  adapter: mysql
  database: RenderCSV_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: RenderCSV_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: RenderCSV_production
  username: root
  password: 
  socket: /tmp/mysql.sock
