development:
  adapter: mysql
  database: PolymorphicAssociations_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: PolymorphicAssociations_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: PolymorphicAssociations_production
  username: root
  password: 
  socket: /tmp/mysql.sock
