development:
  adapter: mysql
  database: TestingIncomingEmail_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: TestingIncomingEmail_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: TestingIncomingEmail_production
  username: root
  password: 
  socket: /tmp/mysql.sock
