development:
  adapter: mysql
  database: CreatingYourOwnRakeTasks_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: CreatingYourOwnRakeTasks_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: CreatingYourOwnRakeTasks_production
  username: root
  password: 
  socket: /tmp/mysql.sock
