development:
  adapter: mysql
  database: WriteTestsForHelpers_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: WriteTestsForHelpers_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: WriteTestsForHelpers_production
  username: root
  password: 
  socket: /tmp/mysql.sock
