organization_name: Rails Security

environment: development

server_port: 4567
log_directory: log
log_level: Logger::DEBUG
ssl_enabled: false

cas_database:
  adapter: sqlite3
  database: db/cas.db
  timeout: 5000

cas_adapter:
  adapter: ldap
  host: localhost
  port: 10389
  prefix: uid=
  base: dc=railssecurity,dc=org