development:
  adapter: mysql
  database: ActsAsVersioned_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: ActsAsVersioned_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: ActsAsVersioned_production
  username: root
  password: 
  socket: /tmp/mysql.sock
